import type { Category, Product } from "@/types/catalog";

export const categories: Category[] = [
  {
    slug: "jersey",
    name: "Jersey",
    description: "Premium football jerseys, fanwear, and collector-ready drops.",
    coverImage: "/assets/categories/jersey-cover.svg",
    subcategories: [
      {
        slug: "world-cup-2026",
        name: "World Cup 2026",
        description: "Fresh national team kits for the next global stage.",
        coverImage: "/assets/subcategories/world-cup-2026.svg",
      },
      {
        slug: "flags",
        name: "Flags",
        description: "Flag-themed fanwear and collectible essentials.",
        coverImage: "/assets/subcategories/flags.svg",
      },
      {
        slug: "original-copy-jersey",
        name: "Original Copy Jersey",
        description: "Higher-finish replicas with premium trims and feel.",
        coverImage: "/assets/subcategories/original-copy-jersey.svg",
      },
    ],
  },
];

const baseStory = (country: string, detailA: string, detailB: string) => [
  {
    title: "Fabric Feel",
    text: `Lightweight, breathable knit designed for all-day comfort in Bangladesh's weather. ${detailA}`,
    image: "/assets/story/fabric-detail.svg",
  },
  {
    title: "Finish & Print",
    text: `Sharp crest work, balanced color treatment, and long-wear printing meant to stay crisp. ${detailB}`,
    image: "/assets/story/finish-detail.svg",
  },
  {
    title: `${country} Matchday Look`,
    text: `A premium fanwear silhouette that pairs cleanly with denim, cargos, or shorts for a full matchday fit.`,
    image: "/assets/story/matchday-look.svg",
  },
];

export const products: Product[] = [
  {
    slug: "argentina-home",
    name: "Argentina Home Jersey",
    shortName: "Argentina Home",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 455,
    compareAtPrice: 500,
    stock: 11,
    badge: "Best Seller",
    gender: "Unisex",
    featured: true,
    isNew: true,
    isPremium: true,
    description: "A premium Argentina home jersey with a modern supporter fit and breathable match-ready fabric.",
    highlights: ["Breathable performance knit", "Premium crest finish", "Regular fanwear fit"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Sky Blue", hex: "#79b7f3" },
      { name: "White", hex: "#ffffff" },
      { name: "Black", hex: "#111827" },
    ],
    images: [
      "/assets/products/argentina-home.jpg",
      "/assets/products/argentina-home-back.jpg",
      "/assets/products/argentina-home-detail.jpg",
    ],
    story: baseStory("Argentina", "Soft stretch adds comfort through longer wear.", "Contrast detailing keeps the classic palette premium."),
  },
  {
    slug: "argentina-away",
    name: "Argentina Away Jersey",
    shortName: "Argentina Away",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 426,
    compareAtPrice: 497,
    stock: 11,
    gender: "Unisex",
    featured: true,
    isNew: true,
    description: "A darker away-kit expression for fans who prefer a sharper, modern look.",
    highlights: ["Soft touch fabric", "Athletic visual lines", "Easy everyday styling"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Navy", hex: "#1d3557" },
      { name: "Silver", hex: "#d1d5db" },
    ],
    images: [
      "/assets/products/argentina-away.jpg",
      "/assets/products/argentina-away-back.jpg",
      "/assets/products/argentina-away-detail.jpg",
    ],
    story: baseStory("Argentina", "Built to feel light without looking flat.", "Reflective-looking accents lift the away palette."),
  },
  {
    slug: "brazil-home",
    name: "Brazil Home Jersey",
    shortName: "Brazil Home",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 455,
    compareAtPrice: 500,
    stock: 11,
    badge: "Fan Favorite",
    gender: "Unisex",
    featured: true,
    isPremium: true,
    description: "The iconic yellow home kit reworked for a sharper, premium supporter wardrobe.",
    highlights: ["Bright team color", "Comfort knit", "Premium badge application"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Brazil Yellow", hex: "#facc15" },
      { name: "Green", hex: "#15803d" },
      { name: "Blue", hex: "#2563eb" },
    ],
    images: [
      "/assets/products/brazil-home.jpg",
      "/assets/products/brazil-home-back.jpg",
      "/assets/products/brazil-home-detail.jpg",
    ],
    story: baseStory("Brazil", "The knit stays airy while keeping good structure.", "Graphic details keep the jersey vivid and clean."),
  },
  {
    slug: "brazil-away",
    name: "Brazil Away Jersey",
    shortName: "Brazil Away",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 426,
    compareAtPrice: 495,
    stock: 11,
    gender: "Unisex",
    isNew: true,
    description: "A sleek away design for supporters who want a cooler palette and premium cut.",
    highlights: ["Modern away tone", "Smooth hand feel", "Collector-friendly finish"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Royal Blue", hex: "#1d4ed8" },
      { name: "Green", hex: "#166534" },
    ],
    images: [
      "/assets/products/brazil-away.jpg",
      "/assets/products/brazil-away-back.jpg",
      "/assets/products/brazil-away-detail.jpg",
    ],
    story: baseStory("Brazil", "Keeps its drape well with repeated use.", "Away tones are handled with a clean low-noise finish."),
  },
  {
    slug: "germany-home",
    name: "Germany Home Jersey",
    shortName: "Germany Home",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 445,
    compareAtPrice: 529,
    stock: 11,
    gender: "Unisex",
    featured: true,
    description: "A crisp monochrome-forward Germany home jersey with refined trim detailing.",
    highlights: ["Minimal premium design", "Breathable build", "Versatile styling"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "White", hex: "#f9fafb" },
      { name: "Black", hex: "#111827" },
      { name: "Red", hex: "#dc2626" },
    ],
    images: [
      "/assets/products/germany-home.jpg",
      "/assets/products/germany-home-back.jpg",
      "/assets/products/germany-home-detail.jpg",
    ],
    story: baseStory("Germany", "Designed to feel structured without feeling heavy.", "Subtle trim work keeps the jersey elevated."),
  },
  {
    slug: "portugal-home",
    name: "Portugal Home Jersey",
    shortName: "Portugal Home",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 326,
    compareAtPrice: 400,
    stock: 11,
    gender: "Unisex",
    isPremium: true,
    description: "Deep red tones and premium visual balance make this a standout Portugal piece.",
    highlights: ["Rich color saturation", "Soft breathable body", "Matchday-to-street styling"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Crimson", hex: "#991b1b" },
      { name: "Green", hex: "#166534" },
      { name: "Gold", hex: "#f59e0b" },
    ],
    images: [
      "/assets/products/portugal-home.jpg",
      "/assets/products/portugal-home-back.jpg",
      "/assets/products/portugal-home-detail.jpg",
    ],
    story: baseStory("Portugal", "Built for comfort while keeping a polished silhouette.", "Trim accents add depth without looking loud."),
  },
  {
    slug: "spain-home",
    name: "Spain Home Jersey",
    shortName: "Spain Home",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 455,
    compareAtPrice: 520,
    stock: 11,
    gender: "Unisex",
    isNew: true,
    description: "A bold red supporter jersey with sharp contrast elements for modern styling.",
    highlights: ["Balanced fit", "Strong color depth", "Comfort-first fabrication"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Red", hex: "#b91c1c" },
      { name: "Navy", hex: "#1e3a8a" },
      { name: "Gold", hex: "#d97706" },
    ],
    images: [
      "/assets/products/spain-home.jpg",
      "/assets/products/spain-home-back.jpg",
      "/assets/products/spain-home-detail.jpg",
    ],
    story: baseStory("Spain", "A soft interior feel reduces scratchiness on long wear.", "Graphics are tuned for a premium, not flashy, finish."),
  },
  {
    slug: "argentina-flag",
    name: "Argentina Flag Jersey",
    shortName: "Argentina Flag",
    categorySlug: "jersey",
    subcategorySlug: "flags",
    price: 80,
    compareAtPrice: 100,
    stock: 5,
    gender: "Unisex",
    featured: true,
    description: "Flag-inspired fanwear piece with bold color blocking and lightweight comfort.",
    highlights: ["Casual supporter piece", "Soft knit", "Easy layering"],
    sizes: ["3.5 x 3"],
    colors: [
      { name: "Sky Blue", hex: "#7dd3fc" },
      { name: "White", hex: "#ffffff" },
    ],
    images: [
      "/assets/products/argentina-flag.jpg",
      "/assets/products/argentina-flag-back.jpg",
      "/assets/products/argentina-flag-detail.jpg",
    ],
    story: baseStory("Argentina", "More casual than match kits, still premium in feel.", "Color blocks are tuned for everyday wearability."),
  },
  {
    slug: "brazil-flag",
    name: "Brazil Flag Jersey",
    shortName: "Brazil Flag",
    categorySlug: "jersey",
    subcategorySlug: "flags",
    price: 80,
    compareAtPrice: 100,
    stock: 5,
    gender: "Unisex",
    description: "Green-and-yellow fanwear built to stand out while staying comfortable.",
    highlights: ["Expressive palette", "Soft midweight knit", "Easy fanwear styling"],
    sizes: ["3.5 x 3"],
    colors: [
      { name: "Green", hex: "#15803d" },
      { name: "Yellow", hex: "#facc15" },
    ],
    images: [
      "/assets/products/brazil-flag.jpg",
      "/assets/products/brazil-flag-back.jpg",
      "/assets/products/brazil-flag-detail.jpg",
    ],
    story: baseStory("Brazil", "Comfort-focused cut makes it simple to wear often.", "Color blocking is bold without becoming harsh."),
  },
  {
    slug: "germany-flag",
    name: "Germany Flag Jersey",
    shortName: "Germany Flag",
    categorySlug: "jersey",
    subcategorySlug: "flags",
    price: 80,
    compareAtPrice: 100,
    stock: 5,
    gender: "Unisex",
    description: "A strong black-led fanwear piece with classic German flag accents.",
    highlights: ["Strong neutral base", "Comfort fit", "Statement supporter style"],
    sizes: ["3.5 x 3"],
    colors: [
      { name: "Black", hex: "#111827" },
      { name: "Red", hex: "#dc2626" },
      { name: "Gold", hex: "#eab308" },
    ],
    images: [
      "/assets/products/germany-flag.jpg",
      "/assets/products/germany-flag-back.jpg",
      "/assets/products/germany-flag-detail.jpg",
    ],
    story: baseStory("Germany", "Everyday-wear comfort with a more graphic presentation.", "Accent lines keep the design sharp and clean."),
  },
  {
    slug: "argentina-original-copy",
    name: "Argentina Original Copy Jersey",
    shortName: "Argentina Original Copy",
    categorySlug: "jersey",
    subcategorySlug: "original-copy-jersey",
    price: 1026,
    compareAtPrice: 1390,
    stock: 11,
    badge: "Premium Copy",
    gender: "Unisex",
    isPremium: true,
    description: "Higher-finish Argentina replica with upgraded detailing, trims, and premium hand feel.",
    highlights: ["Premium copy finish", "Enhanced detailing", "Collector-tier feel"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Sky Blue", hex: "#7dd3fc" },
      { name: "White", hex: "#ffffff" },
      { name: "Black", hex: "#111827" },
    ],
    images: [
      "/assets/products/argentina-original-copy.jpg",
      "/assets/products/argentina-original-copy-back.jpg",
      "/assets/products/argentina-original-copy-detail.jpg",
    ],
    story: baseStory("Argentina", "A denser, more premium feel for collectors and repeat buyers.", "Trim accuracy and texture are emphasized."),
  },
  {
    slug: "brazil-original-copy",
    name: "Brazil Original Copy Jersey",
    shortName: "Brazil Original Copy",
    categorySlug: "jersey",
    subcategorySlug: "original-copy-jersey",
    price: 1026,
    compareAtPrice: 1390,
    stock: 11,
    badge: "Premium Copy",
    gender: "Unisex",
    featured: true,
    isPremium: true,
    description: "Premium-finish Brazil replica with elevated trims and a more refined visual texture.",
    highlights: ["Collector-grade presentation", "Enhanced badge finish", "Premium supporter fit"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Brazil Yellow", hex: "#facc15" },
      { name: "Green", hex: "#15803d" },
      { name: "Blue", hex: "#2563eb" },
    ],
    images: [
      "/assets/products/brazil-original-copy.jpg",
      "/assets/products/brazil-original-copy-back.jpg",
      "/assets/products/brazil-original-copy-detail.jpg",
    ],
    story: baseStory("Brazil", "The touch and drape are tuned for a more premium segment.", "Extra-finished visual details set it apart."),
  },
];

