import type { Category, Product } from "@/types/catalog";

export const categories: Category[] = [
  {
    slug: "jersey",
    name: "Jersey",
    description: "Premium football jerseys, original copy kits, flag fanwear, and collector-ready drops delivered across Bangladesh.",
    coverImage: "/assets/categories/jersey-cover.svg",
    subcategories: [
      {
        slug: "world-cup-2026",
        name: "World Cup 2026",
        description: "Fresh World Cup 2026 national team jerseys for Bangladesh football fans who want a clean matchday look.",
        coverImage: "/assets/subcategories/world-cup-2026.svg",
      },
      {
        slug: "flags",
        name: "Flags",
        description: "Affordable flag-themed fanwear and collectible supporter pieces for football fans across Bangladesh.",
        coverImage: "/assets/subcategories/flags.svg",
      },
      {
        slug: "original-copy-jersey",
        name: "Original Copy Jersey",
        description: "Premium original copy football jerseys with higher-finish fabric, trims, and collector-friendly details.",
        coverImage: "/assets/subcategories/original-copy-jersey.svg",
      },
    ],
  },
];

const baseStory = (country: string, detailA: string, detailB: string) => [
  {
    title: "Fabric Feel",
    text: `Lightweight, breathable knit designed for all-day comfort in Bangladesh's weather. ${detailA}`,
    image: "/assets/story/fabric-detail.svg",
  },
  {
    title: "Finish & Print",
    text: `Sharp crest work, balanced color treatment, and long-wear printing meant to stay crisp. ${detailB}`,
    image: "/assets/story/finish-detail.svg",
  },
  {
    title: `${country} Matchday Look`,
    text: `A premium fanwear silhouette that pairs cleanly with denim, cargos, or shorts for a full matchday fit.`,
    image: "/assets/story/matchday-look.svg",
  },
];

export const products: Product[] = [
  {
    slug: "argentina-home",
    name: "Argentina Home Jersey",
    shortName: "Argentina Home",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 450,
    compareAtPrice: 500,
    stock: 11,
    badge: "Best Seller",
    gender: "Unisex",
    featured: true,
    isNew: true,
    isPremium: true,
    description: "A premium Argentina home jersey for Bangladesh fans, built with breathable fabric, clean crest detail, and a modern supporter fit.",
    highlights: ["Breathable performance knit", "Premium crest finish", "Regular fanwear fit"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Sky Blue", hex: "#79b7f3" },
      { name: "White", hex: "#ffffff" },
      { name: "Black", hex: "#111827" },
    ],
    images: [
      "/assets/products/argentina-home.jpg",
      "/assets/products/argentina-home-back.jpg",
      "/assets/products/argentina-home-detail.jpg",
    ],
    story: baseStory("Argentina", "Soft stretch adds comfort through longer wear.", "Contrast detailing keeps the classic palette premium."),
  },
  {
    slug: "argentina-away",
    name: "Argentina Away Jersey",
    shortName: "Argentina Away",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 450,
    compareAtPrice: 500,
    stock: 11,
    gender: "Unisex",
    featured: true,
    isNew: true,
    description: "A darker Argentina away jersey for fans in Bangladesh who prefer a sharper modern look with soft fabric and easy styling.",
    highlights: ["Soft touch fabric", "Athletic visual lines", "Easy everyday styling"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Navy", hex: "#1d3557" },
      { name: "Silver", hex: "#d1d5db" },
    ],
    images: [
      "/assets/products/argentina-away.jpg",
      "/assets/products/argentina-away-back.jpg",
      "/assets/products/argentina-away-detail.jpg",
    ],
    story: baseStory("Argentina", "Built to feel light without looking flat.", "Reflective-looking accents lift the away palette."),
  },
  {
    slug: "brazil-home",
    name: "Brazil Home Jersey",
    shortName: "Brazil Home",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 450,
    compareAtPrice: 500,
    stock: 11,
    badge: "Fan Favorite",
    gender: "Unisex",
    featured: true,
    isPremium: true,
    description: "The iconic Brazil yellow home jersey reworked for a sharper premium supporter wardrobe with comfortable Bangladesh-weather wear.",
    highlights: ["Bright team color", "Comfort knit", "Premium badge application"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Brazil Yellow", hex: "#facc15" },
      { name: "Green", hex: "#15803d" },
      { name: "Blue", hex: "#2563eb" },
    ],
    images: [
      "/assets/products/brazil-home.jpg",
      "/assets/products/brazil-home-back.jpg",
      "/assets/products/brazil-home-detail.jpg",
    ],
    story: baseStory("Brazil", "The knit stays airy while keeping good structure.", "Graphic details keep the jersey vivid and clean."),
  },
  {
    slug: "brazil-away",
    name: "Brazil Away Jersey",
    shortName: "Brazil Away",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 450,
    compareAtPrice: 500,
    stock: 11,
    gender: "Unisex",
    isNew: true,
    description: "A sleek Brazil away jersey for supporters who want a cooler palette, premium cut, and reliable everyday comfort.",
    highlights: ["Modern away tone", "Smooth hand feel", "Collector-friendly finish"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Royal Blue", hex: "#1d4ed8" },
      { name: "Green", hex: "#166534" },
    ],
    images: [
      "/assets/products/brazil-away.jpg",
      "/assets/products/brazil-away-back.jpg",
      "/assets/products/brazil-away-detail.jpg",
    ],
    story: baseStory("Brazil", "Keeps its drape well with repeated use.", "Away tones are handled with a clean low-noise finish."),
  },
  {
    slug: "germany-home",
    name: "Germany Home Jersey",
    shortName: "Germany Home",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 450,
    compareAtPrice: 520,
    stock: 11,
    gender: "Unisex",
    featured: true,
    description: "A crisp Germany home jersey with refined trim detailing, breathable structure, and a versatile look for Bangladesh matchdays.",
    highlights: ["Minimal premium design", "Breathable build", "Versatile styling"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "White", hex: "#f9fafb" },
      { name: "Black", hex: "#111827" },
      { name: "Red", hex: "#dc2626" },
    ],
    images: [
      "/assets/products/germany-home.jpg",
      "/assets/products/germany-home-back.jpg",
      "/assets/products/germany-home-detail.jpg",
    ],
    story: baseStory("Germany", "Designed to feel structured without feeling heavy.", "Subtle trim work keeps the jersey elevated."),
  },
  {
    slug: "portugal-home",
    name: "Portugal Home Jersey",
    shortName: "Portugal Home",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 350,
    compareAtPrice: 400,
    stock: 11,
    gender: "Unisex",
    isPremium: true,
    description: "A standout Portugal home jersey with deep red tones, premium visual balance, and soft breathable comfort.",
    highlights: ["Rich color saturation", "Soft breathable body", "Matchday-to-street styling"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Crimson", hex: "#991b1b" },
      { name: "Green", hex: "#166534" },
      { name: "Gold", hex: "#f59e0b" },
    ],
    images: [
      "/assets/products/portugal-home.jpg",
      "/assets/products/portugal-home-back.jpg",
      "/assets/products/portugal-home-detail.jpg",
    ],
    story: baseStory("Portugal", "Built for comfort while keeping a polished silhouette.", "Trim accents add depth without looking loud."),
  },
  {
    slug: "spain-home",
    name: "Spain Home Jersey",
    shortName: "Spain Home",
    categorySlug: "jersey",
    subcategorySlug: "world-cup-2026",
    price: 450,
    compareAtPrice: 520,
    stock: 11,
    gender: "Unisex",
    isNew: true,
    description: "A bold Spain home jersey for Bangladesh football fans, designed with strong color depth and comfort-first fabric.",
    highlights: ["Balanced fit", "Strong color depth", "Comfort-first fabrication"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Red", hex: "#b91c1c" },
      { name: "Navy", hex: "#1e3a8a" },
      { name: "Gold", hex: "#d97706" },
    ],
    images: [
      "/assets/products/spain-home.jpg",
      "/assets/products/spain-home-back.jpg",
      "/assets/products/spain-home-detail.jpg",
    ],
    story: baseStory("Spain", "A soft interior feel reduces scratchiness on long wear.", "Graphics are tuned for a premium, not flashy, finish."),
  },
  {
    slug: "argentina-flag",
    name: "Argentina Flag",
    shortName: "Argentina Flag",
    categorySlug: "jersey",
    subcategorySlug: "flags",
    price: 100,
    compareAtPrice: 130,
    stock: 5,
    gender: "Unisex",
    featured: true,
    description: "An affordable Argentina flag fanwear piece with bold color blocking, lightweight comfort, and easy Bangladesh delivery.",
    highlights: ["Casual supporter piece", "Soft knit", "Easy layering"],
    sizes: ["3.5 x 3"],
    colors: [
      { name: "Sky Blue", hex: "#7dd3fc" },
      { name: "White", hex: "#ffffff" },
    ],
    images: [
      "/assets/products/argentina-flag.jpg",
      "/assets/products/argentina-flag-back.jpg",
      "/assets/products/argentina-flag-detail.jpg",
    ],
    story: baseStory("Argentina", "More casual than match kits, still premium in feel.", "Color blocks are tuned for everyday wearability."),
  },
  {
    slug: "brazil-flag",
    name: "Brazil Flag",
    shortName: "Brazil Flag",
    categorySlug: "jersey",
    subcategorySlug: "flags",
    price: 100,
    compareAtPrice: 130,
    stock: 5,
    gender: "Unisex",
    description: "Green-and-yellow Brazil flag fanwear built to stand out at matches, watch parties, and casual outings.",
    highlights: ["Expressive palette", "Soft midweight knit", "Easy fanwear styling"],
    sizes: ["3.5 x 3"],
    colors: [
      { name: "Green", hex: "#15803d" },
      { name: "Yellow", hex: "#facc15" },
    ],
    images: [
      "/assets/products/brazil-flag.jpg",
      "/assets/products/brazil-flag-back.jpg",
      "/assets/products/brazil-flag-detail.jpg",
    ],
    story: baseStory("Brazil", "Comfort-focused cut makes it simple to wear often.", "Color blocking is bold without becoming harsh."),
  },
  {
    slug: "germany-flag",
    name: "Germany Flag",
    shortName: "Germany Flag",
    categorySlug: "jersey",
    subcategorySlug: "flags",
    price: 100,
    compareAtPrice: 130,
    stock: 5,
    gender: "Unisex",
    description: "A strong black-led Germany flag fanwear piece with classic accents, comfortable fit, and collector appeal.",
    highlights: ["Strong neutral base", "Comfort fit", "Statement supporter style"],
    sizes: ["3.5 x 3"],
    colors: [
      { name: "Black", hex: "#111827" },
      { name: "Red", hex: "#dc2626" },
      { name: "Gold", hex: "#eab308" },
    ],
    images: [
      "/assets/products/germany-flag.jpg",
      "/assets/products/germany-flag-back.jpg",
      "/assets/products/germany-flag-detail.jpg",
    ],
    story: baseStory("Germany", "Everyday-wear comfort with a more graphic presentation.", "Accent lines keep the design sharp and clean."),
  },
  {
    slug: "argentina-original-copy",
    name: "Argentina Original Copy Jersey",
    shortName: "Argentina Original Copy",
    categorySlug: "jersey",
    subcategorySlug: "original-copy-jersey",
    price: 1250,
    compareAtPrice: 1390,
    stock: 11,
    badge: "Premium Copy",
    gender: "Unisex",
    isPremium: true,
    description: "A higher-finish Argentina original copy jersey with upgraded detailing, premium trims, and a collector-grade hand feel.",
    highlights: ["Premium copy finish", "Enhanced detailing", "Collector-tier feel"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Sky Blue", hex: "#7dd3fc" },
      { name: "White", hex: "#ffffff" },
      { name: "Black", hex: "#111827" },
    ],
    images: [
      "/assets/products/argentina-original-copy.jpg",
      "/assets/products/argentina-original-copy-back.jpg",
      "/assets/products/argentina-original-copy-detail.jpg",
    ],
    story: baseStory("Argentina", "A denser, more premium feel for collectors and repeat buyers.", "Trim accuracy and texture are emphasized."),
  },
  {
    slug: "brazil-original-copy",
    name: "Brazil Original Copy Jersey",
    shortName: "Brazil Original Copy",
    categorySlug: "jersey",
    subcategorySlug: "original-copy-jersey",
    price: 1250,
    compareAtPrice: 1390,
    stock: 11,
    badge: "Premium Copy",
    gender: "Unisex",
    featured: true,
    isPremium: true,
    description: "A premium-finish Brazil original copy jersey with elevated trims, refined texture, and a standout supporter look.",
    highlights: ["Collector-grade presentation", "Enhanced badge finish", "Premium supporter fit"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Brazil Yellow", hex: "#facc15" },
      { name: "Green", hex: "#15803d" },
      { name: "Blue", hex: "#2563eb" },
    ],
    images: [
      "/assets/products/brazil-original-copy.jpg",
      "/assets/products/brazil-original-copy-back.jpg",
      "/assets/products/brazil-original-copy-detail.jpg",
    ],
    story: baseStory("Brazil", "The touch and drape are tuned for a more premium segment.", "Extra-finished visual details set it apart."),
  },
];

